Repository PaperMC/Paper, pull requests merged in 2020-11, with the labels that each got.

#4733 OBFHELPERS
  Spigot-Server-Patches/0209-Fix-exploit-that-allowed-colored-signs-to-be-created.patch
  Spigot-Server-Patches/0327-Limit-Client-Sign-length-more.patch
  Spigot-Server-Patches/0511-Fix-Per-World-Difficulty-Remembering-Difficulty.patch
  Spigot-Server-Patches/0549-Brand-support.patch
Labels: ready for core

#4730 [CI-SKIP] Fix version for groovy artifact (1.16.4)
  README.md
Labels: ready for core

#4593 Toggle for removing existing dragon
  Spigot-Server-Patches/0594-Toggle-for-removing-existing-dragon.patch
Labels: ready for core, type: bug

#4710 Fix client lag on advancement loading
  Spigot-Server-Patches/0595-Fix-client-lag-on-advancement-loading.patch
Labels: ready for core

#3612 Added custom ranges to beacons
  Spigot-API-Patches/0233-Beacon-API-custom-effect-ranges.patch
  Spigot-Server-Patches/0597-Beacon-API-custom-effect-ranges.patch
Labels: type: feature

#4750 Add ignore discounts API
  Spigot-API-Patches/0232-Add-ignore-discounts-API.patch
  Spigot-Server-Patches/0594-Add-ignore-discounts-API.patch
Labels: type: feature

#4192 Zero pad chunks before saving
  Spigot-Server-Patches/0599-Zero-pad-chunks-before-saving-them-to-the-disk.patch
Labels: status: rebase required, type: feature

#4768 Add `curl` requirement for building paper.
  CONTRIBUTING.md
  scripts/requireDeps.sh
Labels: ready for core, type: bug, type: feature

#4770 Location#getHighestLocation should support Upstream API
  Spigot-API-Patches/0178-Add-Heightmap-API.patch
Labels: ready for core, type: bug, type: feature

#4765 Patch 2 references an invalid variable
  Spigot-Server-Patches/0002-Paper-config-files.patch
  Spigot-Server-Patches/0004-MC-Utils.patch
  Spigot-Server-Patches/0362-Anti-Xray.patch
Labels: ready for core, type: bug

#4615 ✨ Villager resetOffers API
  Spigot-API-Patches/0229-Villager-resetOffers.patch
  Spigot-Server-Patches/0583-Villager-resetOffers.patch
Labels: billy-pr, ready for core, type: feature

#4158 Add Wandering Trader spawn rate config options
  Spigot-Server-Patches/0600-Add-Wandering-Trader-spawn-rate-config-options.patch
Labels: ready for core, type: feature

#4738 Significantly improve performance of the end generation
  Spigot-Server-Patches/0601-Significantly-improve-performance-of-the-end-generat.patch
Labels: ready for core, type: performance

#4796 [CI-SKIP] Fix an error in the commit message when updating upstream
  scripts/upstreamCommit.sh
Labels: needs testing, status: accepted, type: opinion, type: security

#4072 Preserve order and allow multiple equal blocks in hidden-blocks of Anti-Xray
  Spigot-Server-Patches/0362-Anti-Xray.patch
Labels: ready for core, type: feature

#4803 Expose world spawn angle
  Spigot-Server-Patches/0602-Expose-world-spawn-angle.patch
Labels: type: feature

#3946 Add getDestroySpeed to Block API
  Spigot-API-Patches/0237-Add-Destroy-Speed-API.patch
  Spigot-Server-Patches/0603-Add-Destroy-Speed-API.patch
Labels: ready for core, status: rebase required, type: feature
