Repository PaperMC/Paper, pull requests merged in 2020-10, with the labels that each got.

#4604 Lazily track plugin scoreboards by default
  Spigot-Server-Patches/0581-Lazily-track-plugin-scoreboards-by-default.patch
Labels: hacktoberfest-accepted, type: performance

#4621 Add a missing return in Eigencraft redstone
  Spigot-Server-Patches/0565-Optimize-redstone-algorithm.patch
Labels: type: bug, type: performance

#4613 Fix deop kicking non-whitelisted player when white list is not enabled
  Spigot-Server-Patches/0583-Fix-deop-kicking-non-whitelisted-player-when-white-l.patch
Labels: billy-pr, hacktoberfest-accepted, type: bug

#4606 Clarify the JavaDocs for Entity.getEntitySpawnReason()
  Spigot-API-Patches/0230-Clarify-the-Javadocs-for-Entity.getEntitySpawnReason.patch
Labels: hacktoberfest-accepted

#4618 Fix CME when adding a passenger during CreatureSpawnEvent (#4616)
  Spigot-Server-Patches/0584-Fix-CME-on-adding-a-passenger-in-CreatureSpawnEvent.patch
Labels: hacktoberfest-accepted, type: bug

#4605 Fix distance in checkHighPriorityChunks (Fixes #4582)
  Spigot-Server-Patches/0488-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
Labels: hacktoberfest-accepted, type: bug

#4611 Fix item locations dropped from campfires
  Spigot-Server-Patches/0591-Fix-item-locations-dropped-from-campfires.patch
Labels: billy-pr, hacktoberfest-accepted, type: bug

#3139 Add player elytra boost API
  Spigot-API-Patches/0230-Player-elytra-boost-API.patch
  Spigot-Server-Patches/0592-Player-elytra-boost-API.patch
Labels: type: feature

#4637 Fixed TileEntityBell memory leak
  Spigot-Server-Patches/0593-Fixed-TileEntityBell-memory-leak.patch
Labels: hacktoberfest-accepted

#4698 Make fireworks call PlayerLaunchProjectileEvent
  Spigot-Server-Patches/0387-PlayerLaunchProjectileEvent.patch
Labels: type: bug

#4681 Avoid crashing clients when fishing loot is empty, Fixes #4235
  Spigot-Server-Patches/0594-Avoid-error-bubbling-up-when-item-stack-is-empty-in-.patch
Labels: hacktoberfest-accepted
