Repository PaperMC/Paper, pull requests merged in 2020-12, with the labels that each got.

#4610 Fix Player#spawnParticle x/y/z precision loss
  Spigot-Server-Patches/0604-Fix-Player-spawnParticle-x-y-z-precision-loss.patch
Labels: ready for core, type: bug

#3910 Add LivingEntity#clearActiveItem
  Spigot-API-Patches/0237-Add-LivingEntity-clearActiveItem.patch
  Spigot-Server-Patches/0605-Add-LivingEntity-clearActiveItem.patch
Labels: ready for core, status: rebase required, type: feature

#3807 Add PlayerItemCooldownEvent
  LICENSE.md
  Spigot-API-Patches/0199-Add-item-slot-convenience-methods.patch
  Spigot-API-Patches/0238-Add-PlayerItemCooldownEvent.patch
  Spigot-Server-Patches/0606-Add-PlayerItemCooldownEvent.patch
Labels: ready for core, type: feature

#4000 Add lightning API to get/set flash count and life ticks
  Spigot-API-Patches/0239-More-lightning-API.patch
  Spigot-Server-Patches/0607-More-lightning-API.patch
Labels: ready for core, status: rebase required, type: feature

#3350 Add legacy plugin count to metrics
  Spigot-Server-Patches/0005-Paper-Metrics.patch
  Spigot-Server-Patches/0437-Improved-Watchdog-Support.patch
Labels: ready for core, status: rebase required, type: feature

#4187 Climbing should not bypass cramming gamerule
  Spigot-Server-Patches/0608-Climbing-should-not-bypass-cramming-gamerule.patch
Labels: ready for core, type: bug

#4206 Add summary to /paper chunkinfo command
  Spigot-Server-Patches/0356-Chunk-debug-command.patch
Labels: type: feature

#4230 Add PlayerShearBlockEvent
  Spigot-API-Patches/0240-Add-PlayerShearBlockEvent.patch
  Spigot-Server-Patches/0610-Add-PlayerShearBlockEvent.patch
Labels: joshie-pr, type: feature

#4801 Fix Delegation to vanilla chunk gen
  Spigot-Server-Patches/0525-Allow-delegation-to-vanilla-chunk-gen.patch
Labels: ready for core, status: accepted, type: bug, version: 1.16

#4834 Turn off spigot verbose world by default
  Spigot-Server-Patches/0612-Set-spigots-verbose-world-setting-to-false-by-def.patch
Labels: status: accepted

#4580 Fix merging spawning values
  Spigot-Server-Patches/0374-implement-optional-per-player-mob-spawns.patch
Labels: type: bug

#4188 Add #getEligibleHumans to SkeletonHorseTrapEvent
  Spigot-API-Patches/0124-SkeletonHorse-Additions.patch
  Spigot-Server-Patches/0250-SkeletonHorse-Additions.patch
  Spigot-Server-Patches/0394-Optimise-IEntityAccess-getPlayerByUUID.patch
  Spigot-Server-Patches/0457-Add-phantom-creative-and-insomniac-controls.patch
  Spigot-Server-Patches/0608-Climbing-should-not-bypass-cramming-gamerule.patch
Labels: ready for core, type: feature

#4871 Fix MC-181190 curing zombie villager discount exploit
  Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
Labels: billy-pr

#4873 Fix curing villager makes equipment disappear
  Spigot-Server-Patches/0614-Fix-curing-villager-makes-equipment-disappear.patch
Labels: billy-pr

#4872 Fix MC-4 (oldest MC bug) item position desync
  Spigot-Server-Patches/0616-MC-4-Fix-item-position-desync.patch
Labels: billy-pr

#4712 PlayerChunkLoadEvent / PlayerChunkUnloadEvent
  Spigot-API-Patches/0242-Player-Chunk-Load-Unload-Events.patch
  Spigot-Server-Patches/0617-Player-Chunk-Load-Unload-Events.patch
Labels: ready for core, type: feature

#4913 Make Paper Safe Again
  Spigot-API-Patches/0022-Use-ASM-for-event-executors.patch
Labels: status: accepted, type: security, we must go deeper

#4889 Expose LivingEntity hurt direction
  Spigot-API-Patches/0243-Expose-LivingEntity-hurt-direction.patch
  Spigot-Server-Patches/0620-Expose-LivingEntity-hurt-direction.patch
Labels: status: accepted

#4938 Fix lead dupe
  Spigot-Server-Patches/0458-Fix-numerous-item-duplication-issues-and-teleport-is.patch
  Spigot-Server-Patches/0508-Ensure-Entity-AABB-s-are-never-invalid.patch
  Spigot-Server-Patches/0574-Expose-the-Entity-Counter-to-allow-plugins-to-use-va.patch
  Spigot-Server-Patches/0576-Entity-isTicking.patch
  Spigot-Server-Patches/0579-Fix-CME-on-adding-a-passenger-in-CreatureSpawnEvent.patch
Labels: ready for core

#4945 [CI-SKIP] Deprecate the view distance APIs on Player
  Spigot-API-Patches/0010-Add-player-view-distance-API.patch
  Spigot-API-Patches/0021-Complete-resource-pack-API.patch
  Spigot-API-Patches/0041-Add-String-based-Action-Bar-API.patch
  Spigot-API-Patches/0087-Player.setPlayerProfile-API.patch
  Spigot-API-Patches/0146-Expose-attack-cooldown-methods-for-Player.patch
  Spigot-API-Patches/0194-Add-Player-Client-Options-API.patch
  Spigot-API-Patches/0221-Brand-support.patch
  Spigot-API-Patches/0230-Player-elytra-boost-API.patch
Labels: ready for core

#3815 add PlayerTradeEvent
  Spigot-API-Patches/0244-Added-PlayerTradeEvent.patch
  Spigot-Server-Patches/0623-Added-PlayerTradeEvent.patch
Labels: ready for core, status: rebase required, type: feature

#4936 Add OBSTRUCTED result to BedEnterResult enum
  Spigot-API-Patches/0244-Add-OBSTRUCTED-reason-to-BedEnterResult.patch
  Spigot-Server-Patches/0622-Add-OBSTRUCTED-reason-to-BedEnterResult.patch
Labels: ready for core

#4808 Add cancellable TargetHitEvent for when Target Blocks are hit by Projectiles
  Spigot-API-Patches/0246-Add-TargetHitEvent-API.patch
  Spigot-Server-Patches/0625-Implement-TargetHitEvent.patch
Labels: ready for core

#3989 Fix harming potion dupe
  Spigot-Server-Patches/0627-Fix-harming-potion-dupe.patch
Labels: ready for core, status: rebase required, type: bug
