Repository PaperMC/Paper, pull requests merged in 2020-09, with the labels that each got.

#1731 Cache block data strings
  Spigot-Server-Patches/0575-Cache-block-data-strings.patch
Labels: type: performance

#4210 Fix Entity Teleportation and cancel velocity if teleported
  Spigot-Server-Patches/0575-Fix-Entity-Teleportation-and-cancel-velocity-if-tele.patch
Labels: type: bug, type: performance, upstream: bukkit, upstream: vanilla

#4213 Add additional open container api to HumanEntity
  Spigot-API-Patches/0226-Add-additional-open-container-api-to-HumanEntity.patch
  Spigot-Server-Patches/0579-Add-additional-open-container-api-to-HumanEntity.patch
Labels: type: feature

#4232 Expose the Entity Counter to allow plugins to use valid and non-conflicting Entity Ids
  Spigot-API-Patches/0227-Expose-the-Entity-Counter-to-allow-plugins-to-use-va.patch
  Spigot-Server-Patches/0581-Expose-the-Entity-Counter-to-allow-plugins-to-use-va.patch
Labels: type: feature
