Repository PaperMC/Paper, pull requests merged in 2020-08, with the labels that each got.

#4146 Fix regex mistake in CB NBT int deserialization
  Spigot-Server-Patches/0552-Fix-regex-mistake-in-CB-NBT-int-deserialization.patch
Labels: bug

#4189 Fix javadocs failing jenkins builds
  Spigot-API-Patches/0218-Add-setMaxPlayers-API.patch
Labels: billy-pr, version: 1.16

#4185 Add playPickupItemAnimation to LivingEntity
  Spigot-API-Patches/0219-Add-playPickupItemAnimation-to-LivingEntity.patch
  Spigot-Server-Patches/0559-Add-playPickupItemAnimation-to-LivingEntity.patch
Labels: type: feature

#4073 Make engine-mode 2 truly random
  Spigot-Server-Patches/0368-Anti-Xray.patch
Labels: type: feature

#4056 Port Eigencraft to 1.16
  Spigot-Server-Patches/0565-Optimize-redstone-algorithm.patch
Labels: type: performance

#4168 Pass entity to PortalCreateEvent if caused by one
  Spigot-Server-Patches/0568-PortalCreateEvent-needs-to-know-its-entity.patch
Labels: type: bug

#4169 Restore overrides changing visibility
  Spigot-Server-Patches/0004-MC-Utils.patch
Labels: type: bug

#3990 Fix PersistentDataContainer contract violation (_->!null returns null)
  Spigot-Server-Patches/0180-API-to-get-a-BlockState-without-a-snapshot.patch
  Spigot-Server-Patches/0395-Optimize-Hoppers.patch
Labels: type: bug

#4170 fix #4144
  Spigot-API-Patches/0053-PlayerAttemptPickupItemEvent.patch
Labels: type: bug

#2230 Add BellRingEvent for village bells
  Spigot-API-Patches/0221-Add-BellRingEvent.patch
  Spigot-Server-Patches/0565-Add-BellRingEvent.patch
Labels: status: rebase required, type: feature

#4181 Add zombie targets turtle egg config
  Spigot-Server-Patches/0565-Add-zombie-targets-turtle-egg-config.patch
Labels: type: feature

#4180 Add more Evoker API
  Spigot-API-Patches/0223-Add-more-Evoker-API.patch
  Spigot-Server-Patches/0573-Add-more-Evoker-API.patch
Labels: type: feature

#4016 Get an ItemStack's Name as Translatable Component
  Spigot-API-Patches/0224-Add-a-way-to-get-translation-keys-for-blocks-entitie.patch
  Spigot-Server-Patches/0574-Add-a-way-to-get-translation-keys-for-blocks-entitie.patch
Labels: type: feature

#3835 Create HoverEvent from ItemStack Entity
  LICENSE.md
  Spigot-API-Patches/0225-Create-HoverEvent-from-ItemStack-Entity.patch
  Spigot-Server-Patches/0575-Create-HoverEvent-from-ItemStack-Entity.patch
Labels: type: feature
