Repository PaperMC/Paper, pull requests merged in 2021-06, with the labels that each got.

#5776 Fix dangerous end portal logic
  Spigot-Server-Patches/0655-added-Wither-API.patch
  Spigot-Server-Patches/0755-Fix-dangerous-end-portal-logic.patch
Labels: type: bug

#4837 per world spawn limits
  Spigot-Server-Patches/0758-add-per-world-spawn-limits.patch
Labels: status: accepted, type: bug

#5816 Fix recursive connection call causing StackOverflowException
  patches/server/0306-Optimize-Network-Manager-and-add-advanced-packet-sup.patch
Labels: version: 1.17

#5814 ReAdded PreCreatureSpawnEvent from removed
  patches/removed/1.17/0187-PreCreatureSpawnEvent.patch
  patches/server/0330-PreCreatureSpawnEvent.patch
Labels: version: 1.17

#5829 Re-add Chunk Priority/Urgency System
  patches/server/0468-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
Labels: version: 1.17
