Repository PaperMC/Paper, pull requests merged in 2021-03, with the labels that each got.

#4970 Fix username connecting with no texture being overwritten by usercache
  LICENSE.md
  Spigot-Server-Patches/0152-Basic-PlayerProfile-API.patch
Labels: status: accepted

#5294 Fix Material#getTranslationKey for Block Materials
  Spigot-API-Patches/0276-Cache-the-result-of-Material-isBlock.patch
  Spigot-Server-Patches/0566-Add-a-way-to-get-translation-keys-for-blocks-entitie.patch
  Spigot-Server-Patches/0574-Expose-the-Entity-Counter-to-allow-plugins-to-use-va.patch
Labels: type: bug

#4714 Fixed furnace cook-speed multiplier losing precision while calculating cook times
  Spigot-Server-Patches/0288-Implement-furnace-cook-speed-multiplier-API.patch
  Spigot-Server-Patches/0629-Cache-burn-durations.patch
Labels: type: bug

#4590 MC-29274: Fix Wither hostility towards players
  Spigot-Server-Patches/0682-MC-29274-Fix-Wither-hostility-towards-players.patch
Labels: type: bug

#4719 Throw proper exception on empty JsonList file
  Spigot-Server-Patches/0683-Throw-proper-exception-on-empty-JsonList-file.patch
Labels: status: accepted

#4602 Improve ServerGUI
  Spigot-Server-Patches/0684-Improve-ServerGUI.patch
Labels: type: feature

#3805 added PlayerNameEntityEvent
  Spigot-API-Patches/0278-added-PlayerNameEntityEvent.patch
  Spigot-Server-Patches/0688-added-PlayerNameEntityEvent.patch
Labels: status: rebase required, type: feature

#3834 Add Block#isValidTool
  Spigot-API-Patches/0280-Add-Block-isValidTool.patch
  Spigot-Server-Patches/0691-Add-Block-isValidTool.patch
Labels: status: rebase required, type: feature

#3143 Allow using signs inside of spawn protection
  Spigot-Server-Patches/0692-Allow-using-signs-inside-spawn-protection.patch
Labels: status: rebase required, type: bug

#5014 Implement Keyed on World
  Spigot-API-Patches/0281-Implement-Keyed-on-World.patch
  Spigot-Server-Patches/0693-Implement-Keyed-on-World.patch
Labels: status: accepted

#5345 Removal from the MIT list
  LICENSE.md
Labels: requires core approval

#5352 Add Item Rarity API
  Spigot-API-Patches/0282-Item-Rarity-API.patch
  Spigot-Server-Patches/0695-Item-Rarity-API.patch
Labels: status: accepted, type: feature

#5009 Add per-command perms for paper command
  Spigot-Server-Patches/0002-Paper-config-files.patch
  Spigot-Server-Patches/0006-Add-MinecraftKey-Information-to-Objects.patch
  Spigot-Server-Patches/0254-Ignore-Dead-Entities-in-entityList-iteration.patch
  Spigot-Server-Patches/0357-Chunk-debug-command.patch
  Spigot-Server-Patches/0369-Asynchronous-chunk-IO-and-loading.patch
  Spigot-Server-Patches/0371-Reduce-sync-loads.patch
  Spigot-Server-Patches/0472-Fix-Light-Command.patch
  Spigot-Server-Patches/0511-Paper-dumpitem-command.patch
  Spigot-Server-Patches/0678-Clear-SyncLoadInfo.patch
Labels: status: accepted

#5278 [CI-SKIP] 🚀 Upgrade to new form-based templates
  .github/ISSUE_TEMPLATE/behavior-bug---plugin-incompatibility.md
  .github/ISSUE_TEMPLATE/behavior-bug-or-plugin-incompatibility.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/performance-problem.md
  .github/ISSUE_TEMPLATE/performance-problem.yml
  .github/ISSUE_TEMPLATE/server-crash---stacktrace.md
  .github/ISSUE_TEMPLATE/server-crash-or-stacktrace.yml
Labels: requires core approval, status: accepted

#5350 Fix annotations so Inventory#getContents returns non-null array with nullable type
  Spigot-API-Patches/0282-fix-Inventory-getContents-null-annotations.patch
Labels: status: rebase required

#5166 Drop carried item when player has disconnected (#5036)
  Spigot-Server-Patches/0697-Drop-carried-item-when-player-has-disconnected.patch
Labels: status: rebase required

#5348 Optimize short circuit evaluation of sign check
  Spigot-Server-Patches/0691-Allow-using-signs-inside-spawn-protection.patch
Labels: status: rebase required
