Repository PaperMC/Paper, pull requests merged in 2021-01, with the labels that each got.

#4965 Add API to get the Material of Boats and Minecarts
  Spigot-API-Patches/0248-Add-API-to-get-Material-from-Boats-and-Minecarts.patch
  Spigot-Server-Patches/0628-Implement-API-to-get-Material-from-Boats-and-Minecar.patch
Labels: type: feature

#4634 Allow disabling mob spawner spawn egg transformation
  Spigot-Server-Patches/0631-Allow-disabling-mob-spawner-spawn-egg-transformation.patch
Labels: ready for core, type: feature

#4911 JavaDoc fixes
  Spigot-API-Patches/0050-Fix-upstream-javadoc-warnings-and-errors.patch
  Spigot-API-Patches/0087-Player.setPlayerProfile-API.patch
  Spigot-API-Patches/0096-Expand-World.spawnParticle-API-and-add-Builder.patch
  Spigot-API-Patches/0146-Expose-attack-cooldown-methods-for-Player.patch
  Spigot-API-Patches/0194-Add-Player-Client-Options-API.patch
  Spigot-API-Patches/0201-World-view-distance-api.patch
  Spigot-API-Patches/0206-Add-Raw-Byte-ItemStack-Serialization.patch
  Spigot-API-Patches/0221-Brand-support.patch
  Spigot-API-Patches/0230-Player-elytra-boost-API.patch
Labels: ready for core

#2459 Add PlayerFlowerPotManipulateEvent
  Spigot-API-Patches/0249-Add-PlayerFlowerPotManipulateEvent.patch
  Spigot-Server-Patches/0632-Implement-PlayerFlowerPotManipulateEvent.patch
Labels: ready for core, status: rebase required, type: feature

#3597 Fix interact event not being called in adventure
  Spigot-Server-Patches/0633-Fix-interact-event-not-being-called-in-adventure.patch
Labels: ready for core, status: rebase required, type: bug

#3838 added can/setBreakDoor methods (#3837)
  LICENSE.md
  Spigot-API-Patches/0250-Zombie-API-breaking-doors.patch
  Spigot-Server-Patches/0634-Zombie-API-breaking-doors.patch
Labels: ready for core, status: rebase required, type: feature

#3931 fix for nerfed slime mobs splitting (#3930)
  Spigot-Server-Patches/0635-Fix-nerfed-slime-when-splitting.patch
Labels: ready for core, type: bug

#4074 Add Anti-Xray bypass permission
  Spigot-Server-Patches/0362-Anti-Xray.patch
  Spigot-Server-Patches/0364-Configurable-projectile-relative-velocity.patch
  Spigot-Server-Patches/0368-Asynchronous-chunk-IO-and-loading.patch
  Spigot-Server-Patches/0371-Implement-alternative-item-despawn-rate.patch
  Spigot-Server-Patches/0374-implement-optional-per-player-mob-spawns.patch
  Spigot-Server-Patches/0377-Generator-Settings.patch
  Spigot-Server-Patches/0383-Add-option-to-disable-pillager-patrols.patch
  Spigot-Server-Patches/0388-MC-145656-Fix-Follow-Range-Initial-Target.patch
  Spigot-Server-Patches/0389-Optimize-Hoppers.patch
  Spigot-Server-Patches/0400-Tracking-Range-Improvements.patch
  Spigot-Server-Patches/0409-Add-option-to-nerf-pigmen-from-nether-portals.patch
  Spigot-Server-Patches/0415-Configurable-chance-of-villager-zombie-infection.patch
  Spigot-Server-Patches/0418-Pillager-patrol-spawn-settings-and-per-player-option.patch
  Spigot-Server-Patches/0428-Increase-Light-Queue-Size.patch
  Spigot-Server-Patches/0457-Add-phantom-creative-and-insomniac-controls.patch
  Spigot-Server-Patches/0466-Use-distance-map-to-optimise-entity-tracker.patch
  Spigot-Server-Patches/0469-No-Tick-view-distance-implementation.patch
  Spigot-Server-Patches/0484-Workaround-for-Client-Lag-Spikes-MC-162253.patch
  Spigot-Server-Patches/0494-Delay-Chunk-Unloads-based-on-Player-Movement.patch
  Spigot-Server-Patches/0506-Limit-lightning-strike-effect-distance.patch
  Spigot-Server-Patches/0559-Add-zombie-targets-turtle-egg-config.patch
  Spigot-Server-Patches/0561-Optimize-redstone-algorithm.patch
  Spigot-Server-Patches/0594-Toggle-for-removing-existing-dragon.patch
  Spigot-Server-Patches/0600-Add-Wandering-Trader-spawn-rate-config-options.patch
  Spigot-Server-Patches/0608-Climbing-should-not-bypass-cramming-gamerule.patch
  Spigot-Server-Patches/0613-Fix-curing-zombie-villager-discount-exploit.patch
  Spigot-Server-Patches/0631-Allow-disabling-mob-spawner-spawn-egg-transformation.patch
Labels: ready for core, type: feature

#4626 Add EntityLoadCrossbowEvent
  Spigot-API-Patches/0251-Add-EntityLoadCrossbowEvent.patch
  Spigot-Server-Patches/0636-Add-EntityLoadCrossbowEvent.patch
Labels: ready for core

#4744 Use ItemStack#setAmount for ShapelessRecipe
  Spigot-API-Patches/0168-Add-ItemStack-Recipe-API-helper-methods.patch
Labels: ready for core, type: feature

#4767 Support spawning item stacks
  Spigot-API-Patches/0179-Mob-Spawner-API-Enhancements.patch
  Spigot-Server-Patches/0344-Mob-Spawner-API-Enhancements.patch
Labels: ready for core, type: feature

#4820 Add BlockFailedDispenseEvent
  Spigot-API-Patches/0254-Add-BlockFailedDispenseEvent.patch
  Spigot-Server-Patches/0641-Implemented-BlockFailedDispenseEvent.patch
Labels: ready for core

#5019 Empty commands shall not be dispatched
  Spigot-Server-Patches/0647-Empty-commands-shall-not-be-dispatched.patch
Labels: type: bug

#4956 Add sendOpLevel API
  Spigot-API-Patches/0259-Add-sendOpLevel-API.patch
  Spigot-Server-Patches/0650-Add-sendOpLevel-API.patch
Labels: type: feature

#4333 Add StructureLocateEvent
  Spigot-API-Patches/0260-Add-StructureLocateEvent.patch
  Spigot-Server-Patches/0651-Add-StructureLocateEvent.patch
Labels: type: feature

#4764 Collision option for requiring a player participant
  Spigot-Server-Patches/0652-Collision-option-for-requiring-a-player-participant.patch
Labels: type: feature

#3814 added Wither API
  Spigot-API-Patches/0264-added-Wither-API.patch
  Spigot-Server-Patches/0658-added-Wither-API.patch
Labels: status: rebase required, type: feature

#3615 Add PlayerChangeBeaconEffectEvent
  Spigot-API-Patches/0265-Added-PlayerChangeBeaconEffectEvent.patch
  Spigot-Server-Patches/0659-Added-firing-of-PlayerChangeBeaconEffectEvent.patch
Labels: type: feature

#4809 Add toggle for always placing the dragon egg
  Spigot-Server-Patches/0662-Add-toggle-for-always-placing-the-dragon-egg.patch
Labels: type: feature

#2962 Skip distance map update when world spawning is disabled
  Spigot-Server-Patches/0664-Skip-distance-map-update-when-spawning-disabled.patch
Labels: status: rebase required, type: performance

#4614 EntityMoveEvent
  Spigot-API-Patches/0268-EntityMoveEvent.patch
  Spigot-Server-Patches/0666-EntityMoveEvent.patch
Labels: type: feature

#5082 Inline shift fields in EnumDirection
  Spigot-Server-Patches/0669-Inline-shift-direction-fields.patch
Labels: type: performance
