Repository PaperMC/Paper, pull requests merged in 2021-05, with the labels that each got.

#5020 Add more Wandering Trader API
  Spigot-API-Patches/0294-Add-more-WanderingTrader-API.patch
  Spigot-Server-Patches/0721-Add-more-WanderingTrader-API.patch
Labels: status: accepted, status: rebase required

#5030 Add Adventure message to PlayerAdvancementDoneEvent
  Spigot-API-Patches/0296-Add-Adventure-message-to-PlayerAdvancementDoneEvent.patch
  Spigot-Server-Patches/0725-Add-Adventure-message-to-PlayerAdvancementDoneEvent.patch
Labels: status: rebase required

#4832 Add cause to Weather/ThunderChangeEvents
  Spigot-API-Patches/0310-Add-cause-to-Weather-ThunderChangeEvents.patch
  Spigot-Server-Patches/0744-Add-cause-to-Weather-ThunderChangeEvents.patch
Labels: status: accepted, status: rebase required, type: feature

#5334 Items Merge Through Walls Fix (fixes #5204)
  Spigot-Server-Patches/0750-Add-option-to-fix-items-merging-through-walls.patch
Labels: status: rebase required
