Repository PaperMC/Paper, pull requests merged in 2021-07, with the labels that each got.

#6076 Fix Bossbar updating (closes #6061)
  patches/server/0010-Adventure.patch
Labels: type: bug

#4766 fixed kick event leave message
  patches/server/0725-Fixes-kick-event-leave-message-not-being-sent.patch
Labels: type: bug

#4835 Add config for mobs immune to default effects
  patches/server/0726-Add-config-for-mobs-immune-to-default-effects.patch
Labels: status: accepted, type: feature

#6257 Move "use-display-name-in-quit-message" to settings namespace
  patches/server/0004-Paper-config-files.patch
  patches/server/0010-Adventure.patch
  patches/server/0059-Default-loading-permissions.yml-before-plugins.patch
  patches/server/0074-Sanitise-RegionFileCache-and-make-configurable.patch
  patches/server/0083-Configurable-Player-Collision.patch
  patches/server/0092-Don-t-save-empty-scoreboard-teams-to-scoreboard.dat.patch
  patches/server/0102-Add-setting-for-proxy-online-mode-status.patch
  patches/server/0104-Configurable-packet-in-spam-threshold.patch
  patches/server/0105-Configurable-flying-kick-messages.patch
  patches/server/0136-Add-configuration-option-to-prevent-player-names-fro.patch
  patches/server/0156-Allow-specifying-a-custom-authentication-servers-dow.patch
  patches/server/0188-Make-player-data-saving-configurable.patch
  patches/server/0209-Configurable-Alternative-LootPool-Luck-Formula.patch
  patches/server/0241-Break-up-and-make-tab-spam-limits-configurable.patch
  patches/server/0245-Add-Early-Warning-Feature-to-WatchDog.patch
  patches/server/0260-Asynchronous-chunk-IO-and-loading.patch
  patches/server/0273-Configurable-connection-throttle-kick-message.patch
  patches/server/0280-Add-Velocity-IP-Forwarding-Support.patch
  patches/server/0294-Make-the-default-permission-message-configurable.patch
  patches/server/0299-Book-Size-Limits.patch
  patches/server/0388-Optimise-TickListServer-by-rewriting-it.patch
  patches/server/0397-Mid-Tick-Chunk-Tasks-Speed-up-processing-of-chunk-lo.patch
  patches/server/0399-Add-tick-times-API-and-mspt-command.patch
  patches/server/0442-Protect-Bedrock-and-End-Portal-Frames-from-being-des.patch
  patches/server/0446-Add-option-for-console-having-all-permissions.patch
  patches/server/0459-Fix-piston-physics-inconsistency-MC-188840.patch
  patches/server/0501-Incremental-player-saving.patch
  patches/server/0512-Prevent-headless-pistons-from-being-created.patch
  patches/server/0515-Buffer-joins-to-world.patch
  patches/server/0530-Lazily-track-plugin-scoreboards-by-default.patch
  patches/server/0568-Limit-recipe-packets.patch
  patches/server/0570-MC-4-Fix-item-position-desync.patch
  patches/server/0653-Enhance-console-tab-completions-for-brigadier-comman.patch
  patches/server/0707-Make-item-validations-configurable.patch
  patches/server/0714-Deobfuscate-stacktraces-in-log-messages-crash-report.patch
  patches/server/0721-Config-option-for-named-entity-death-logging.patch
Labels: status: rebase required
