Repository PaperMC/Paper, pull requests merged in 2021-04, with the labels that each got.

#5269 Update the view distance before scheduling chunk loads
  Spigot-Server-Patches/0486-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
Labels: requires core approval

#5535 fix non-dummy objectives not updating
  Spigot-Server-Patches/0574-Lazily-track-plugin-scoreboards-by-default.patch
Labels: status: accepted, type: bug

#3850 Adding more world API methods
  Spigot-API-Patches/0289-More-World-API.patch
  Spigot-Server-Patches/0714-More-World-API.patch
Labels: status: rebase required, type: feature

#4935 Added PlayerBedFailEnterEvent
  Spigot-API-Patches/0290-Added-PlayerBedFailEnterEvent.patch
  Spigot-Server-Patches/0715-Added-PlayerBedFailEnterEvent.patch
Labels: status: accepted

#5540 Fix anchor respawn acting as a bed respawn when using the end portal
  Spigot-Server-Patches/0717-Fix-anchor-respawn-acting-as-a-bed-respawn-from-the-.patch
Labels: status: accepted, upstream: bukkit
