Repository PaperMC/Paper, pull requests merged in 2021-12, with the labels that each got.

#5074 Optimize HashMapPalette
  patches/api/0344-Add-player-health-update-API.patch
  patches/server/0822-Add-player-health-update-API.patch
  patches/server/0823-Optimize-HashMapPalette.patch
Labels: status: accepted

#7026 Fix possible NPEs with trade events
  patches/server/0401-Async-command-map-building.patch
  patches/server/0422-Implement-Brigadier-Mojang-API.patch
  patches/server/0573-Add-PlayerTradeEvent-and-PlayerPurchaseEvent.patch
  patches/server/0847-fixup-Async-command-map-building.patch
Labels: version: 1.17

#6950 Update Optimise chunk tick iteration
  patches/removed/1.18/0765-Optimise-chunk-tick-iteration.patch
  patches/server/0006-MC-Utils.patch
  patches/server/0172-PlayerNaturallySpawnCreaturesEvent.patch
  patches/server/0435-Optimize-anyPlayerCloseEnoughForSpawning-to-use-dist.patch
  patches/server/0827-Optimise-chunk-tick-iteration.patch
Labels: version: 1.18

#7042 [ci skip] Add nullable annotation to field
  patches/server/0242-Add-Debug-Entities-option-to-debug-dupe-uuid-issues.patch
  patches/server/0393-Optimize-Collision-to-not-load-chunks.patch
Labels: version: 1.18

#6468 Fix entity type tags suggestions in selectors
  patches/server/0836-Fix-entity-type-tags-suggestions-in-selectors.patch
Labels: status: accepted

#6466 Fix bees aging inside hives
  patches/server/0270-Honor-EntityAgeable.ageLock.patch
  patches/server/0840-Fix-bees-aging-inside-hives.patch
Labels: status: accepted

#6226 Check player world in endPortalSoundRadius
  patches/server/0842-Check-player-world-in-endPortalSoundRadius.patch
Labels: status: accepted
