Repository PaperMC/Paper, pull requests merged in 2022-12, with the labels that each got.

#4722 Player Entity Tracking Events
  patches/api/0413-Player-Entity-Tracking-Events.patch
  patches/server/0951-Player-Entity-Tracking-Events.patch
Labels: type: feature

#8674 Fix explosion yield with new gamerules
  patches/server/0948-Fix-explosion-yield-with-new-gamerules.patch
Labels: build-pr-jar

#8710 Fix OfflinePlayer getPlayerProfile return type
  patches/api/0092-Player.setPlayerProfile-API.patch
Labels: build-pr-jar

#6448 Add config option for spider worldborder climbing
  patches/server/0004-Paper-config-files.patch
  patches/server/0951-Add-config-option-for-spider-worldborder-climbing.patch
Labels: build-pr-jar

#5357 Set player allowFlight fall damage
  patches/api/0424-Flying-Fall-Damage-API.patch
  patches/server/0954-Flying-Fall-Damage.patch
Labels: status: accepted

#6613 Rework filtering spawn egg and tile entity nbt config
  patches/server/0004-Paper-config-files.patch
  patches/server/0110-Filter-bad-data-from-ArmorStand-and-SpawnEgg-items.patch
  patches/server/0110-Filter-bad-tile-entity-nbt-data-from-falling-blocks.patch
  patches/server/0844-FallingBlock-auto-expire-setting.patch
  patches/server/0956-config-for-disabling-entity-tag-tags.patch
Labels: status: accepted
