Repository PaperMC/Paper, pull requests merged in 2022-06, with the labels that each got.

#6360 Add numeric string completion suggestions as int suggestions
  patches/server/0618-Allow-for-Component-suggestion-tooltips-in-AsyncTabC.patch
  patches/server/0628-fix-PlayerItemHeldEvent-firing-twice.patch
  patches/server/0635-add-RespawnFlags-to-PlayerRespawnEvent.patch
  patches/server/0648-additions-to-PlayerGameModeChangeEvent.patch
  patches/server/0659-Add-PlayerKickEvent-causes.patch
  patches/server/0676-Ensure-disconnect-for-book-edit-is-called-on-main.patch
  patches/server/0680-Adds-PlayerArmSwingEvent.patch
  patches/server/0681-Fixes-kick-event-leave-message-not-being-sent.patch
  patches/server/0808-Optimise-collision-checking-in-player-move-packet-ha.patch
  patches/server/0839-Kick-on-main-for-illegal-chars.patch
  patches/server/0888-Prevent-tile-entity-copies-loading-chunks.patch
  patches/server/0891-Pass-ServerLevel-for-gamerule-callbacks.patch
  patches/server/0904-Do-not-accept-invalid-client-settings.patch
Labels: needs testing

#6974 [ci skip] Changing the order of the rebase with autosquash command in the contributing.md
  CONTRIBUTING.md
Labels: status: accepted

#7943 Add WardenAngerChangeEvent
  patches/api/0385-Add-WardenAngerChangeEvent.patch
  patches/server/0910-Add-WardenAngerChangeEvent.patch
Labels: status: rebase required
