Repository PaperMC/Paper, pull requests merged in 2022-10, with the labels that each got.

#8097 Fix custom piglin interest items
  patches/server/0922-Fix-custom-piglin-loved-items.patch
Labels: hacktoberfest-accepted

#8096 EntityPickupItemEvent fixes
  patches/server/0923-EntityPickupItemEvent-fixes.patch
Labels: hacktoberfest-accepted

#8030 Add missing structure set seed configs
  patches/server/0810-Add-config-for-stronghold-seed.patch
  patches/server/0810-Add-missing-structure-set-seed-configs.patch
Labels: status: rebase required

#5053 fixed VehicleEntityCollisionEvent not getting called in every case
  patches/server/0930-fixed-entity-vehicle-collision-event-not-called.patch
Labels: status: accepted
