Repository PaperMC/Paper, pull requests merged in 2022-09, with the labels that each got.

#8318 Restore no-crash behaviour when read-only config file(s)
  patches/server/0004-Paper-config-files.patch
  patches/server/0691-Allow-skipping-writing-of-comments-to-server.propert.patch
Labels: status: rebase required

#5840 Add custom destroyerIdentity parameter to the sendBlockBreak function
  patches/api/0392-Add-custom-destroyerIdentity-to-sendBlockDamage.patch
  patches/server/0937-Add-custom-destroyerIdentity-to-sendBlockDamage.patch
Labels: status: accepted, status: rebase required

#6371 fire EntityChangeBlockEvent in more places
  patches/server/0939-Fire-EntityChangeBlockEvent-in-more-places.patch
Labels: status: accepted

#8068 Fix Pathfinding After World Has Changed
  patches/api/0004-Add-FastUtil-to-Bukkit.patch
  patches/api/0026-Use-ASM-for-event-executors.patch
  patches/api/0069-Allow-plugins-to-use-SLF4J-for-logging.patch
  patches/api/0076-Expose-client-protocol-version-and-virtual-host.patch
  patches/api/0152-Add-an-API-for-CanPlaceOn-and-CanDestroy-NBT-values.patch
  patches/api/0157-Add-Material-Tags.patch
  patches/api/0169-Add-APIs-to-replace-OfflinePlayer-getLastPlayed.patch
  patches/api/0210-Support-components-in-ItemMeta.patch
  patches/api/0393-Also-load-resources-from-LibraryLoader.patch
  patches/api/0394-Added-byte-array-serialization-deserialization-for-P.patch
  patches/api/0395-Add-a-consumer-parameter-to-ProjectileSource-launchP.patch
  patches/server/0011-Paper-Metrics.patch
  patches/server/0020-Implement-Chunk-Priority-Urgency-System-for-Chunks.patch
  patches/server/0037-Configurable-top-of-nether-void-damage.patch
  patches/server/0043-Disable-explosion-knockback.patch
  patches/server/0051-Use-UserCache-for-player-heads.patch
  patches/server/0056-All-chunks-are-slime-spawn-chunks-toggle.patch
  patches/server/0078-Use-a-Shared-Random-for-Entities.patch
  patches/server/0095-EntityRegainHealthEvent-isFastRegen-API.patch
  patches/server/0099-LootTable-API-Replenishable-Lootables-Feature.patch
  patches/server/0112-Configurable-packet-in-spam-threshold.patch
  patches/server/0113-Configurable-flying-kick-messages.patch
  patches/server/0133-ExperienceOrbs-API-for-Reason-Source-Triggering-play.patch
  patches/server/0151-Block-player-logins-during-server-shutdown.patch
  patches/server/0161-Allow-specifying-a-custom-authentication-servers-dow.patch
  patches/server/0164-Add-PlayerJumpEvent.patch
  patches/server/0167-revert-serverside-behavior-of-keepalives.patch
  patches/server/0170-Prevent-logins-from-being-processed-when-the-player-.patch
  patches/server/0174-AsyncTabCompleteEvent.patch
  patches/server/0178-Add-setPlayerProfile-API-for-Skulls.patch
  patches/server/0188-Ability-to-change-PlayerProfile-in-AsyncPreLoginEven.patch
  patches/server/0189-Player.setPlayerProfile-API.patch
  patches/server/0242-Break-up-and-make-tab-spam-limits-configurable.patch
  patches/server/0245-Add-Debug-Entities-option-to-debug-dupe-uuid-issues.patch
  patches/server/0249-Ability-to-get-Tile-Entities-from-a-chunk-without-sn.patch
  patches/server/0264-Mob-Pathfinding-API.patch
  patches/server/0276-Add-sun-related-API.patch
  patches/server/0282-Add-option-to-prevent-players-from-moving-into-unloa.patch
  patches/server/0290-Don-t-allow-digging-into-unloaded-chunks.patch
  patches/server/0296-Book-Size-Limits.patch
  patches/server/0304-Implement-Brigadier-Mojang-API.patch
  patches/server/0322-Fix-CB-call-to-changed-postToMainThread-method.patch
  patches/server/0399-Load-Chunks-for-Login-Asynchronously.patch
  patches/server/0410-misc-debugging-dumps.patch
  patches/server/0488-Fix-hex-colors-not-working-in-some-kick-messages.patch
  patches/server/0637-Add-raw-address-to-AsyncPlayerPreLoginEvent.patch
  patches/server/0649-Add-Mob-lookAt-API.patch
  patches/server/0710-Left-handed-API.patch
  patches/server/0723-Fix-GameProfileCache-concurrency.patch
  patches/server/0732-Optimise-general-POI-access.patch
  patches/server/0760-Rewrite-dataconverter-system.patch
  patches/server/0761-Use-Velocity-compression-and-cipher-natives.patch
  patches/server/0780-Add-config-option-for-logging-player-ip-addresses.patch
  patches/server/0801-Actually-unload-POI-data.patch
  patches/server/0820-Validate-usernames.patch
  patches/server/0829-Added-getHostname-to-AsyncPlayerPreLoginEvent.patch
  patches/server/0928-Remove-invalid-signature-login-stacktrace.patch
  patches/server/0931-Add-Velocity-IP-Forwarding-Support.patch
  patches/server/0932-Use-thread-safe-random-in-ServerLoginPacketListenerI.patch
Labels: status: rebase required
