Repository PaperMC/Paper, pull requests merged in 2024-05, with the labels that each got.

#10633 Add GameMode#isInvulnerable
  patches/api/0475-Add-GameMode-isInvulnerable.patch
Labels: type: feature

#10632 Add EquipmentSlot#getOppositeHand
  patches/api/0376-Add-EquipmentSlot-convenience-methods.patch
Labels: type: feature

#10638 Expose #hasColor to leather armor
  patches/api/0056-Fix-upstream-javadocs.patch
  patches/api/0475-Expose-hasColor-to-leather-armor.patch
  patches/server/1045-Expose-hasColor-to-leather-armor.patch
Labels: type: feature

#10400 Added API to get player's proxy address
  patches/api/0478-Added-API-to-get-player-ha-proxy-address.patch
  patches/server/1046-Added-API-to-get-player-ha-proxy-address.patch
Labels: type: feature

#10635 Add a way to check whether the chest is blocked
  patches/api/0479-More-Chest-Block-API.patch
  patches/server/1047-More-Chest-Block-API.patch
Labels: type: feature

#10647 Fix BlockStateMeta
  patches/api/0056-Fix-upstream-javadocs.patch
  patches/server/1044-General-ItemMeta-fixes.patch
Labels: type: bug, build-pr-jar

#10667 Fix hopper pull event being skipped after the first call
  patches/server/1020-Optimize-Hoppers.patch
Labels: type: bug

#8235 Brigadier Command Support
  Paper-MojangAPI/build.gradle.kts
  Paper-MojangAPI/src/main/java/com/destroystokyo/paper/brigadier/BukkitBrigadierCommand.java
  Paper-MojangAPI/src/main/java/com/destroystokyo/paper/brigadier/BukkitBrigadierCommandSource.java
  Paper-MojangAPI/src/main/java/com/destroystokyo/paper/event/brigadier/AsyncPlayerSendCommandsEvent.java
  Paper-MojangAPI/src/main/java/com/destroystokyo/paper/event/brigadier/AsyncPlayerSendSuggestionsEvent.java
  Paper-MojangAPI/src/main/java/com/destroystokyo/paper/event/brigadier/CommandRegisteredEvent.java
  Paper-MojangAPI/src/main/java/io/papermc/paper/brigadier/PaperBrigadier.java
  Paper-MojangAPI/src/main/java/io/papermc/paper/brigadier/PaperBrigadierProvider.java
  build.gradle.kts
  patches/api/0480-Brigadier-based-command-API.patch
  patches/server/0020-Plugin-remapping.patch
  patches/server/0092-Configurable-Player-Collision.patch
  patches/server/0231-Add-Early-Warning-Feature-to-WatchDog.patch
  patches/server/0282-Brigadier-Mojang-API.patch
  patches/server/0362-Implement-Mob-Goal-API.patch
  patches/server/0612-Vanilla-command-permission-fixes.patch
  patches/server/0722-Add-support-for-Proxy-Protocol.patch
  patches/server/1011-Use-Velocity-compression-and-cipher-natives.patch
  patches/server/1038-Add-experimental-improved-give-command.patch
  patches/server/1050-Brigadier-based-command-API.patch
  settings.gradle.kts
  test-plugin/build.gradle.kts
  test-plugin/src/main/java/io/papermc/testplugin/TestPlugin.java
  test-plugin/src/main/java/io/papermc/testplugin/TestPluginBootstrap.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/Registration.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/example/ComponentCommandExceptionType.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/example/ExampleAdminCommand.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/example/IceCreamType.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/example/IceCreamTypeArgument.java
  test-plugin/src/main/java/io/papermc/testplugin/brigtests/example/MaterialArgumentType.java
Labels: build-pr-jar

#10696 Fix signed book page serialization
  patches/server/1042-General-ItemMeta-fixes.patch
Labels: build-pr-jar

#10730 Check for more correct profile validation
  patches/api/0060-Basic-PlayerProfile-API.patch
  patches/api/0179-Expose-the-internal-current-tick.patch
  patches/api/0186-Expose-MinecraftServer-isRunning.patch
  patches/api/0192-Add-Mob-Goal-API.patch
  patches/api/0275-Add-basic-Datapack-API.patch
  patches/api/0342-Custom-Potion-Mixes.patch
  patches/api/0405-Folia-scheduler-and-owned-region-API.patch
  patches/server/0072-Handle-Item-Meta-Inconsistencies.patch
  patches/server/0137-Do-not-submit-profile-lookups-to-worldgen-threads.patch
  patches/server/0138-Basic-PlayerProfile-API.patch
  patches/server/0296-Expose-the-internal-current-tick.patch
  patches/server/0332-Expose-MinecraftServer-isRunning.patch
  patches/server/0359-Implement-Mob-Goal-API.patch
  patches/server/0541-Add-basic-Datapack-API.patch
  patches/server/0687-Custom-Potion-Mixes.patch
  patches/server/0858-Fix-BanList-API.patch
Labels: type: bug

#10710 Add an 'empty' RecipeChoice for certain recipes and ingredient slots
  patches/api/0477-Fix-issues-with-recipe-API.patch
  patches/server/1046-Fix-issues-with-Recipe-API.patch
Labels: build-pr-jar

#10740 Fix a few issues with ItemMeta
  patches/api/0056-Fix-upstream-javadocs.patch
  patches/api/0438-add-missing-Experimental-annotations.patch
  patches/api/0472-Expose-hasColor-to-leather-armor.patch
  patches/server/0008-CB-fixes.patch
  patches/server/0072-Handle-Item-Meta-Inconsistencies.patch
  patches/server/0171-Add-ArmorStand-Item-Meta.patch
  patches/server/0692-More-Projectile-API.patch
  patches/server/0857-fix-item-meta-for-tadpole-buckets.patch
  patches/server/0872-Respect-randomizeData-on-more-entities-when-spawning.patch
  patches/server/0943-Fixup-NamespacedKey-handling.patch
  patches/server/0957-Deprecate-ItemStack-setType.patch
  patches/server/1037-improve-checking-handled-tags-in-itemmeta.patch
  patches/server/1038-General-ItemMeta-fixes.patch
  patches/server/1039-Expose-hasColor-to-leather-armor.patch
  patches/server/1046-Fix-equipment-slot-and-group-API.patch
Labels: priority: high

#10731 Fix CraftMetaBlockState for data components
  patches/server/0638-Fix-upstreams-block-state-factories.patch
  patches/server/1038-General-ItemMeta-fixes.patch
Labels: priority: high, build-pr-jar

#10682 Expose anvil cost in the API
  patches/api/0278-More-Enchantment-API.patch
  patches/server/0545-More-Enchantment-API.patch
Labels: status: rebase required

#10795 Fix BlockStateMeta equals
  patches/server/1038-General-ItemMeta-fixes.patch
Labels: build-pr-jar

#10719 Extend Player Interact cancellation to cover Jigsaw blocks
  patches/server/0172-Extend-Player-Interact-cancellation.patch
  patches/server/0934-Dont-resend-blocks-on-interactions.patch
Labels: type: bug, status: rebase required

#10654 Fix more item desync when an event is cancelled
  patches/server/0896-Fix-inventory-desync.patch
  patches/server/0897-Add-titleOverride-to-InventoryOpenEvent.patch
  patches/server/0899-Do-crystal-portal-proximity-check-before-entity-look.patch
  patches/server/0933-Restore-vanilla-entity-drops-behavior.patch
  patches/server/1009-Collision-optimisations.patch
Labels: type: bug

#10794 Only remove worldgen block entity on changed block
  patches/server/0966-Fix-creation-of-invalid-block-entity-during-world-ge.patch
  patches/server/0977-Rewrite-chunk-system.patch
Labels: priority: high

#10814 Allow firework effects with no colors
  patches/api/0481-General-ItemMeta-fixes.patch
Labels: build-pr-jar

#10634 Extend fishing API
  patches/api/0344-More-Projectile-API.patch
  patches/api/0482-Add-missing-fishing-event-state.patch
  patches/server/0691-More-Projectile-API.patch
  patches/server/0836-More-accurate-isInOpenWater-impl.patch
  patches/server/0924-Add-hand-to-fish-event-for-all-player-interactions.patch
  patches/server/1048-Prevent-NPE-if-hooked-entity-was-cleared.patch
  patches/server/1050-Add-missing-fishing-event-state.patch
Labels: type: feature

#10784 Deprecate InvAction#HOTBAR_MOVE_AND_READD
  patches/api/0483-Deprecate-InvAction-HOTBAR_MOVE_AND_READD.patch
  patches/server/1051-Deprecate-InvAction-HOTBAR_MOVE_AND_READD.patch
Labels: build-pr-jar

#10267 Add entity heal API
  patches/api/0292-Missing-Entity-API.patch
  patches/server/0569-Missing-Entity-API.patch
  patches/server/0579-Stinger-API.patch
  patches/server/0611-Improve-and-expand-AsyncCatcher.patch
  patches/server/0691-More-Projectile-API.patch
  patches/server/0756-Add-a-consumer-parameter-to-ProjectileSource-launchP.patch
  patches/server/0771-Add-entity-knockback-API.patch
  patches/server/0788-ItemStack-damage-API.patch
  patches/server/0789-Friction-API.patch
  patches/server/0814-Add-Entity-Body-Yaw-API.patch
  patches/server/0846-Add-method-to-remove-all-active-potion-effects.patch
Labels: type: feature

#10834 Fire TabCompleteEvent for legacy commands
  patches/api/0476-Brigadier-based-command-API.patch
  patches/server/1043-Brigadier-based-command-API.patch
Labels: build-pr-jar
