Repository PaperMC/Paper, pull requests merged in 2024-12, with the labels that each got.

#11776 Fixes totems negating the incorrect item
  paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch
Labels: build-pr-jar

#11782 Fix Inventory#addItem javadoc mismatch with behaviour
  paper-api/src/main/java/org/bukkit/inventory/Inventory.java
Labels: type: bug

#11784 Throw during plugin update folder process on failed file rename/delete
  paper-server/src/main/java/io/papermc/paper/plugin/provider/source/FileProviderSource.java
Labels: type: bug

#11787 Fix recipe book items order
  paper-server/patches/sources/net/minecraft/world/item/crafting/RecipeMap.java.patch
Labels: type: bug

#11785 Correctly die when cancelling EntityResurrectEvent
  paper-server/patches/features/0003-Entity-Activation-Range-2.0.patch
  paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch
Labels: type: bug, build-pr-jar

#11798 Partially revert 083c083188 for Transformation
  paper-api/src/main/java/org/bukkit/util/Transformation.java
Labels: type: bug, build-pr-jar

#11802 Fix 0 parameter in Player#applyMending
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: bug

#11811 [ci skip] Only build PRs on correct label
  .github/workflows/build.yml
Labels: type: bug

#11775 Port basic lookAt methods from Player to Entity
  paper-api/src/main/java/org/bukkit/entity/Entity.java
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntity.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: feature

#11770 Add effective name to ItemStack
  paper-api/src/main/java/org/bukkit/inventory/ItemStack.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftItemStack.java
Labels: type: feature

#11795 Add Registry#getTags
  paper-api/src/main/java/org/bukkit/Registry.java
  paper-server/src/main/java/io/papermc/paper/registry/PaperSimpleRegistry.java
  paper-server/src/main/java/io/papermc/paper/registry/legacy/DelayedRegistry.java
  paper-server/src/main/java/io/papermc/paper/registry/set/NamedRegistryKeySetImpl.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegistry.java
Labels: type: feature

#11791 Fix BlockRedstoneEvent for tripwire hooks
  paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
Labels: type: bug

#11796 For new registry values, allow copying from existing
  paper-api/src/main/java/io/papermc/paper/registry/RegistryBuilderFactory.java
  paper-api/src/main/java/io/papermc/paper/registry/RegistryKey.java
  paper-api/src/main/java/io/papermc/paper/registry/TypedKey.java
  paper-api/src/main/java/io/papermc/paper/registry/event/WritableRegistry.java
  paper-server/patches/features/0017-Moonrise-optimisation-patches.patch
  paper-server/patches/sources/net/minecraft/core/MappedRegistry.java.patch
  paper-server/src/main/java/io/papermc/paper/registry/PaperRegistryBuilderFactory.java
  paper-server/src/main/java/io/papermc/paper/registry/WritableCraftRegistry.java
Labels: type: feature, scope: api

#11807 Expand on entity serialization API
  paper-api/src/main/java/io/papermc/paper/entity/EntitySerializationFlag.java
  paper-api/src/main/java/org/bukkit/UnsafeValues.java
  paper-api/src/main/java/org/bukkit/entity/Entity.java
  paper-server/patches/features/0017-Moonrise-optimisation-patches.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntity.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntitySnapshot.java
  paper-server/src/main/java/org/bukkit/craftbukkit/util/CraftMagicNumbers.java
Labels: type: feature

#11803 Banner pattern registry modification
  paper-api/src/main/java/io/papermc/paper/registry/data/BannerPatternRegistryEntry.java
  paper-api/src/main/java/io/papermc/paper/registry/event/RegistryEvents.java
  paper-server/src/main/java/io/papermc/paper/registry/PaperRegistries.java
  paper-server/src/main/java/io/papermc/paper/registry/data/PaperBannerPatternRegistryEntry.java
Labels: type: feature

#11809 Updated Kyori-Adventure (4.17.0 -> 4.18.0)
  paper-api/build.gradle.kts
  paper-server/build.gradle.kts
  paper-server/src/main/java/io/papermc/paper/adventure/AdventureCodecs.java
  paper-server/src/test/java/io/papermc/paper/adventure/AdventureCodecsTest.java
Labels: type: feature

#11836 fix more incorrect array nullability annotations
  paper-api/src/main/java/com/destroystokyo/paper/event/server/PaperServerListPingEvent.java
  paper-api/src/main/java/org/bukkit/Bukkit.java
  paper-api/src/main/java/org/bukkit/Chunk.java
  paper-api/src/main/java/org/bukkit/Server.java
  paper-api/src/main/java/org/bukkit/World.java
  paper-api/src/main/java/org/bukkit/command/Command.java
  paper-api/src/main/java/org/bukkit/command/CommandExecutor.java
  paper-api/src/main/java/org/bukkit/command/MessageCommandSender.java
  paper-api/src/main/java/org/bukkit/command/MultipleCommandAlias.java
  paper-api/src/main/java/org/bukkit/command/TabCompleter.java
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-api/src/main/java/org/bukkit/event/HandlerList.java
  paper-api/src/main/java/org/bukkit/inventory/EntityEquipment.java
  paper-api/src/main/java/org/bukkit/inventory/ItemCraftResult.java
  paper-api/src/main/java/org/bukkit/inventory/ItemStack.java
  paper-api/src/main/java/org/bukkit/inventory/PlayerInventory.java
  paper-api/src/main/java/org/bukkit/inventory/ShapedRecipe.java
  paper-api/src/main/java/org/bukkit/inventory/view/EnchantmentView.java
  paper-api/src/main/java/org/bukkit/map/MapFont.java
  paper-api/src/main/java/org/bukkit/plugin/java/JavaPlugin.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/Messenger.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/PluginMessageListener.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/PluginMessageRecipient.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/StandardMessenger.java
  paper-api/src/main/java/org/bukkit/util/ChatPaginator.java
  paper-api/src/main/java/org/bukkit/util/noise/OctaveGenerator.java
  paper-api/src/main/java/org/bukkit/util/noise/SimplexNoiseGenerator.java
Labels: status: accepted

#11781 Handle disabled vanilla registry values correctly
  .editorconfig
  paper-server/patches/sources/net/minecraft/core/registries/BuiltInRegistries.java.patch
  paper-server/patches/sources/net/minecraft/resources/RegistryDataLoader.java.patch
  paper-server/src/main/java/io/papermc/paper/registry/PaperRegistryAccess.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftMusicInstrument.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegistry.java
  paper-server/src/main/java/org/bukkit/craftbukkit/enchantments/CraftEnchantment.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/trim/CraftTrimMaterial.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/trim/CraftTrimPattern.java
  paper-server/src/test/java/org/bukkit/registry/RegistryLoadOrderTest.java
Labels: type: bug

#11841 Fix contextual map renderer memory leak
  paper-server/src/main/java/org/bukkit/craftbukkit/map/CraftMapView.java
Labels: status: accepted

#11783 Add DamageType RegistryEvent
  paper-api/src/main/java/io/papermc/paper/InternalAPIBridge.java
  paper-api/src/main/java/io/papermc/paper/registry/data/DamageTypeRegistryEntry.java
  paper-api/src/main/java/io/papermc/paper/registry/event/RegistryEvents.java
  paper-api/src/main/java/org/bukkit/UnsafeValues.java
  paper-api/src/main/java/org/bukkit/damage/DamageEffect.java
  paper-server/src/main/java/io/papermc/paper/PaperServerInternalAPIBridge.java
  paper-server/src/main/java/io/papermc/paper/plugin/entrypoint/LaunchEntryPointHandler.java
  paper-server/src/main/java/io/papermc/paper/registry/PaperRegistries.java
  paper-server/src/main/java/io/papermc/paper/registry/data/PaperDamageTypeRegistryEntry.java
  paper-server/src/main/resources/META-INF/services/io.papermc.paper.InternalAPIBridge
Labels: type: feature

#11813 Directly build Art
  paper-api/src/main/java/io/papermc/paper/registry/data/InlinedRegistryBuilderProvider.java
  paper-api/src/main/java/org/bukkit/Art.java
  paper-server/src/main/java/io/papermc/paper/registry/PaperRegistries.java
  paper-server/src/main/java/io/papermc/paper/registry/data/InlinedRegistryBuilderProviderImpl.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegistry.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPainting.java
  paper-server/src/main/resources/META-INF/services/io.papermc.paper.registry.data.InlinedRegistryBuilderProvider
Labels: type: feature

#11845 Do not spawn fire for visual lightning
  paper-server/patches/sources/net/minecraft/world/entity/LightningBolt.java.patch
Labels: build-pr-jar

#11804 Add datapack registration lifecycle event
  build-data/paper.at
  paper-api/src/main/java/io/papermc/paper/datapack/Datapack.java
  paper-api/src/main/java/io/papermc/paper/datapack/DatapackRegistrar.java
  paper-api/src/main/java/io/papermc/paper/datapack/DatapackSource.java
  paper-api/src/main/java/io/papermc/paper/datapack/DiscoveredDatapack.java
  paper-api/src/main/java/io/papermc/paper/plugin/lifecycle/event/types/LifecycleEvents.java
  paper-server/patches/sources/net/minecraft/server/MinecraftServer.java.patch
  paper-server/patches/sources/net/minecraft/server/commands/ReloadCommand.java.patch
  paper-server/patches/sources/net/minecraft/server/packs/repository/PackRepository.java.patch
  paper-server/patches/sources/net/minecraft/server/packs/repository/ServerPacksSource.java.patch
  paper-server/src/main/java/io/papermc/paper/datapack/PaperDatapack.java
  paper-server/src/main/java/io/papermc/paper/datapack/PaperDatapackRegistrar.java
  paper-server/src/main/java/io/papermc/paper/datapack/PaperDiscoveredDatapack.java
  paper-server/src/main/java/io/papermc/paper/datapack/PluginPackSource.java
Labels: type: feature

#11810 Extend HumanEntity#dropItem API
  paper-api/src/main/java/org/bukkit/entity/HumanEntity.java
  paper-server/patches/sources/net/minecraft/server/level/ServerPlayer.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/player/Player.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java
Labels: type: feature
