Repository PaperMC/Paper, pull requests merged in 2024-09, with the labels that each got.

#11333 Update Alternate Current to v1.9
  patches/server/0005-Paper-config-files.patch
  patches/server/0999-Add-Alternate-Current-redstone-implementation.patch
Labels: build-pr-jar

#9251 Improve console completion with brig suggestions
  patches/server/0508-Enhance-console-tab-completions-for-brigadier-comman.patch
Labels: build-pr-jar

#11380 Set default drop behavior for player deaths
  patches/server/0912-Restore-vanilla-entity-drops-behavior.patch
Labels: build-pr-jar

#11418 Correctly launch WindCharges
  patches/server/0674-More-Projectile-API.patch
  patches/server/0739-Add-a-consumer-parameter-to-ProjectileSource-launchP.patch
  patches/server/0753-Add-entity-knockback-API.patch
  patches/server/0769-ItemStack-damage-API.patch
  patches/server/0770-Friction-API.patch
  patches/server/0794-Add-Entity-Body-Yaw-API.patch
  patches/server/0968-Fix-equipment-slot-and-group-API.patch
  patches/server/1043-Leashable-API.patch
Labels: build-pr-jar

#10387 Add ItemStack array serialization methods
  patches/api/0182-Add-Raw-Byte-ItemStack-Serialization.patch
  patches/api/0202-Add-methods-to-get-translation-keys.patch
  patches/api/0254-Improve-Item-Rarity-API.patch
  patches/api/0272-ItemStack-repair-check-API.patch
  patches/api/0374-ItemStack-damage-API.patch
  patches/api/0418-Allow-proper-checking-of-empty-item-stacks.patch
  patches/api/0442-ItemStack-Tooltip-API.patch
  patches/api/0475-Proxy-ItemStack-to-CraftItemStack.patch
Labels: type: feature

#11424 Fixup command precprocess cancellation
  patches/api/0053-Fix-upstream-javadocs.patch
  patches/api/0182-Add-Raw-Byte-ItemStack-Serialization.patch
  patches/server/1058-Fix-PlayerCommandPreprocessEvent-on-signed-commands.patch
Labels: build-pr-jar

#11425 remove redundant fillUsableCommands call
  patches/server/0965-Brigadier-based-command-API.patch
  patches/server/1006-Fix-entity-type-tags-suggestions-in-selectors.patch
Labels: build-pr-jar

#7305 Add PlayerInsertLecternBookEvent [1.20 port]
  patches/api/0112-Expand-Explosions-API.patch
  patches/api/0493-Add-PlayerInsertLecternBookEvent.patch
  patches/server/0203-Expand-Explosions-API.patch
  patches/server/1063-Add-PlayerInsertLecternBookEvent.patch
Labels: status: accepted
