Repository PaperMC/Paper, pull requests merged in 2025-02, with the labels that each got.

#12053 Add support for lz4 region compression
  paper-server/patches/sources/net/minecraft/world/level/chunk/storage/RegionFileVersion.java.patch
  paper-server/src/main/java/io/papermc/paper/configuration/GlobalConfiguration.java
Labels: build-pr-jar

#12016 Make Sittable interface extend Entity
  paper-api/src/main/java/org/bukkit/entity/Panda.java
  paper-api/src/main/java/org/bukkit/entity/Sittable.java
  paper-server/src/test/java/org/bukkit/craftbukkit/entity/EntityTypesTest.java
Labels: type: feature, scope: api

#12039 Fix #11887
  paper-server/patches/sources/net/minecraft/world/level/block/piston/PistonMovingBlockEntity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java
Labels: type: bug

#12045 Fix Water Animal spawn height option for Squids and Dolphins
  paper-server/patches/sources/net/minecraft/world/entity/animal/AgeableWaterCreature.java.patch
Labels: type: bug

#12040 Prevent duplicate raider in RaidSpawnWaveEvent list
  paper-server/patches/sources/net/minecraft/world/entity/raid/Raid.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java
Labels: type: bug

#12046 Fix EntityBreedEvent cancellation
  paper-server/patches/sources/net/minecraft/world/entity/ai/behavior/VillagerMakeLove.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/animal/Animal.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/animal/Fox.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java
Labels: type: bug

#12024 Deprecate Server#setSpawnRadius
  paper-api/src/main/java/org/bukkit/Bukkit.java
  paper-api/src/main/java/org/bukkit/Server.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
Labels: scope: api

#12091 Add skipTripwireHookPlacementValidation
  paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
  paper-server/src/main/java/io/papermc/paper/configuration/GlobalConfiguration.java
Labels: type: feature

#12098 Fix vanilla map decorations sending when not dirty
  paper-server/patches/sources/net/minecraft/world/level/saveddata/maps/MapItemSavedData.java.patch
Labels: type: bug

#12068 Add Vault block API
  build-data/paper.at
  paper-api/src/main/java/org/bukkit/block/Vault.java
  paper-server/patches/sources/net/minecraft/world/level/block/entity/vault/VaultServerData.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftVault.java
Labels: scope: api

#12025 Add TrialSpawner methods for end of cooldown and next mob spawn time
  build-data/paper.at
  paper-api/src/main/java/org/bukkit/block/TrialSpawner.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftTrialSpawner.java
Labels: type: feature, scope: api

#12090 Add support for rotation argument handling.
  paper-api/src/main/java/io/papermc/paper/command/brigadier/argument/ArgumentTypes.java
  paper-api/src/main/java/io/papermc/paper/command/brigadier/argument/VanillaArgumentProvider.java
  paper-api/src/main/java/io/papermc/paper/command/brigadier/argument/resolvers/RotationResolver.java
  paper-api/src/main/java/io/papermc/paper/math/Rotation.java
  paper-api/src/main/java/io/papermc/paper/math/RotationImpl.java
  paper-api/src/main/java/org/bukkit/Location.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/argument/VanillaArgumentProviderImpl.java
Labels: scope: api

#12125 [ci skip] Clarify getChunkAtAsyncUrgently javadocs
  paper-api/src/main/java/org/bukkit/World.java
Labels: type: documentation, scope: api

#12120 [ci skip] Fix annotation fields used in NMS getBukkitEntity
  paper-server/patches/features/0006-Optimize-Collision-to-not-load-chunks.patch
  paper-server/patches/sources/net/minecraft/server/bossevents/CustomBossEvent.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
Labels: type: bug

#12022 add method on ItemStack to edit pdc
  paper-api/src/main/java/org/bukkit/inventory/ItemStack.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftItemStack.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java
Labels: type: feature, scope: api

#12106 Cleanup damage source a bit
  paper-api/src/main/java/org/bukkit/damage/DamageSource.java
  paper-api/src/main/java/org/bukkit/event/entity/EntityDamageByBlockEvent.java
  paper-api/src/main/java/org/bukkit/event/entity/EntityDamageByEntityEvent.java
  paper-server/patches/features/0016-Moonrise-optimisation-patches.patch
  paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  paper-server/patches/sources/net/minecraft/world/damagesource/DamageSource.java.patch
  paper-server/patches/sources/net/minecraft/world/damagesource/DamageSources.java.patch
  paper-server/patches/sources/net/minecraft/world/effect/PoisonMobEffect.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/Interaction.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/animal/SnowGolem.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/animal/Turtle.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/player/Player.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/projectile/EvokerFangs.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/projectile/ThrownEnderpearl.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/projectile/WitherSkull.java.patch
  paper-server/patches/sources/net/minecraft/world/level/ServerExplosion.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/BedBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/CactusBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/CampfireBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/MagmaBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/PointedDripstoneBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/RespawnAnchorBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/SweetBerryBushBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/entity/ConduitBlockEntity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/damage/CraftDamageSource.java
  paper-server/src/main/java/org/bukkit/craftbukkit/damage/CraftDamageType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftAbstractArrow.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftArrow.java
  paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java
Labels: type: bug

#12113 Add EntityAttemptSmashAttackEvent
  paper-api/src/main/java/io/papermc/paper/event/entity/EntityAttemptSmashAttackEvent.java
  paper-server/patches/sources/net/minecraft/world/item/MaceItem.java.patch
Labels: type: feature, scope: api

#12077 Separate tick count to ensure vanilla parity
  paper-server/patches/features/0003-Entity-Activation-Range-2.0.patch
  paper-server/patches/features/0006-Optimize-Collision-to-not-load-chunks.patch
  paper-server/patches/features/0016-Moonrise-optimisation-patches.patch
  paper-server/patches/features/0019-Add-Alternate-Current-redstone-implementation.patch
  paper-server/patches/features/0024-Incremental-chunk-and-player-saving.patch
  paper-server/patches/sources/net/minecraft/server/level/ServerLevel.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntity.java
Labels: type: bug

#12011 Add EntityEquipmentChangedEvent
  paper-api/src/main/java/com/destroystokyo/paper/event/player/PlayerArmorChangeEvent.java
  paper-api/src/main/java/io/papermc/paper/event/entity/EntityEquipmentChangedEvent.java
  paper-server/patches/sources/net/minecraft/world/entity/LivingEntity.java.patch
Labels: type: feature, scope: api

#12121 Improvement in /plugins command
  paper-server/src/main/java/io/papermc/paper/command/PaperPluginsCommand.java
Labels: type: feature

#12111 Fix PlayerReadyArrowEvent cancellation desync
  paper-server/patches/sources/net/minecraft/world/entity/player/Player.java.patch
Labels: type: bug

#12131 [ci skip] Fix bad world to chunk coordinate example in javadocs
  paper-api/src/main/java/org/bukkit/World.java
Labels: type: documentation, scope: api

#11926 Fixup luck and random implementation in CB loot-tables
  paper-server/patches/sources/net/minecraft/world/level/storage/loot/LootTable.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftLootTable.java
Labels: type: bug

#11954 Don't auto-create any brig redirects
  paper-api/src/main/java/io/papermc/paper/command/brigadier/CommandRegistrationFlag.java
  paper-api/src/main/java/io/papermc/paper/command/brigadier/Commands.java
  paper-server/patches/sources/com/mojang/brigadier/tree/CommandNode.java.patch
  paper-server/patches/sources/net/minecraft/commands/Commands.java.patch
  paper-server/src/main/java/io/papermc/paper/command/brigadier/ApiMirrorRootNode.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PaperBrigadier.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PaperCommands.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PluginCommandMeta.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PluginCommandNode.java
Labels: type: bug

#12013 Allow For Default Titles in InventoryView Builders
  paper-api/src/main/java/org/bukkit/inventory/MenuType.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/InventoryViewBuilder.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/LocationInventoryViewBuilder.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/MerchantInventoryViewBuilder.java
  paper-server/patches/sources/net/minecraft/world/level/block/ChestBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/entity/ChestBlockEntity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMenuType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMerchantCustom.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/util/CraftMenus.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAbstractInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAbstractLocationInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAccessLocationInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftBlockEntityInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftDoubleChestInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftEnchantmentInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftMerchantInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftStandardInventoryViewBuilder.java
Labels: type: feature, scope: api

#12129 Fix `disable-tripwire-updates` option not cancelling tripwire hook updates
  paper-server/patches/sources/net/minecraft/world/level/block/TripWireHookBlock.java.patch
Labels: type: bug

#12136 Readd dead redirect recovery
  paper-server/patches/sources/net/minecraft/commands/Commands.java.patch
Labels: build-pr-jar

#12144 Fix plugin commands
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PaperCommands.java
Labels: build-pr-jar

#12140 Fix getForwards/SidewaysMovement for players
  paper-api/src/main/java/org/bukkit/entity/LivingEntity.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: bug, scope: api

#12149 Fix server crash when no enchantments are present
  paper-server/src/main/java/io/papermc/paper/util/ItemComponentSanitizer.java
Labels: type: bug

#12158 Always pass event block to damage source
  paper-server/patches/sources/net/minecraft/world/damagesource/DamageSource.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/BedBlock.java.patch
  paper-server/patches/sources/net/minecraft/world/level/block/RespawnAnchorBlock.java.patch
Labels: build-pr-jar

#12186 Add config option for failed beehive release cooldowns
  paper-server/patches/sources/net/minecraft/world/level/block/entity/BeehiveBlockEntity.java.patch
  paper-server/src/main/java/io/papermc/paper/configuration/WorldConfiguration.java
Labels: scope: configuration

#12166 Fix first execution of async delayed/repeating tasks being sync
  paper-server/src/main/java/io/papermc/paper/threadedregions/scheduler/FoliaAsyncScheduler.java
Labels: type: bug

#12182 Add a method on Registry to get the size
  paper-api/src/main/java/org/bukkit/Registry.java
  paper-server/src/main/java/io/papermc/paper/registry/legacy/DelayedRegistry.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegistry.java
Labels: scope: api

#12188 Don't process empty rcon commands
  paper-server/patches/sources/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: type: bug

#12189 Deprecate server config getters
  paper-api/src/main/java/org/bukkit/Bukkit.java
  paper-api/src/main/java/org/bukkit/Server.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
Labels: scope: api

#12177 Use MiniMessage#deserialize(String, Pointered) for send messages
  paper-api/src/main/java/org/bukkit/Server.java
  paper-api/src/main/java/org/bukkit/command/CommandSender.java
Labels: scope: api

#12094 Add methods for Creaking
  paper-api/src/main/java/org/bukkit/entity/Creaking.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftCreaking.java
Labels: scope: api

#12161 Fix cancelled HangingPlaceEvent inventory desync
  paper-server/patches/sources/net/minecraft/world/item/HangingEntityItem.java.patch
Labels: type: bug

#12191 make CustomArgumentType use parse(reader,source)
  paper-server/src/main/java/io/papermc/paper/command/brigadier/argument/VanillaArgumentProviderImpl.java
  paper-server/src/main/java/io/papermc/paper/command/brigadier/argument/WrappedArgumentCommandNode.java
Labels: build-pr-jar

#12201 Remove unused light queue size option
  paper-server/src/main/java/io/papermc/paper/configuration/RemovedConfigurations.java
  paper-server/src/main/java/io/papermc/paper/configuration/WorldConfiguration.java
Labels: scope: configuration

#12195 Document replacement for Skull owner profile methods
  paper-api/src/main/java/org/bukkit/block/Skull.java
Labels: type: documentation
