Repository PaperMC/Paper, pull requests merged in 2025-07, with the labels that each got.

#12775 Add support for listening to plugin messages
  paper-api/src/main/java/org/bukkit/plugin/messaging/Messenger.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/PluginMessageListener.java
  paper-api/src/main/java/org/bukkit/plugin/messaging/StandardMessenger.java
  paper-server/patches/features/0032-Improve-keepalive-ping-system.patch
  paper-server/patches/sources/net/minecraft/server/network/CommonListenerCookie.java.patch
  paper-server/patches/sources/net/minecraft/server/network/ServerCommonPacketListenerImpl.java.patch
  paper-server/patches/sources/net/minecraft/server/network/ServerConfigurationPacketListenerImpl.java.patch
  paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  paper-server/src/main/java/io/papermc/paper/connection/DisconnectionReason.java
  paper-server/src/main/java/io/papermc/paper/connection/PaperPlayerConfigurationConnection.java
  paper-server/src/main/java/io/papermc/paper/connection/PluginMessageBridgeImpl.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: publish-pr

#12783 Fix quitmessage nullability issues
  paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: publish-pr

#12794 Fix incorrect createPath overload arguments, fixes #12043
  paper-server/patches/sources/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch
Labels: type: bug

#12788 Dried Ghast events and Happy Ghast spawn reason
  paper-api/src/main/java/org/bukkit/event/entity/CreatureSpawnEvent.java
  paper-server/patches/sources/net/minecraft/world/level/block/DriedGhastBlock.java.patch
Labels: priority: high
