Repository PaperMC/Paper, pull requests merged in 2025-01, with the labels that each got.

#11858 CraftEntity - Fix retain passengers teleport flag
  build-data/paper.at
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntity.java
Labels: type: bug

#11897 Fix TargetHitEvent#getSignalStrength() post-hard-fork
  paper-server/patches/sources/net/minecraft/world/level/block/TargetBlock.java.patch
Labels: type: bug, priority: high, build-pr-jar

#11865 Fix MapCanvas#drawImage
  paper-server/src/main/java/org/bukkit/craftbukkit/map/CraftMapCanvas.java
Labels: type: bug, priority: high, build-pr-jar

#11923 Update CustomTimingsHandler Nag Message
  paper-api/src/main/java/org/spigotmc/CustomTimingsHandler.java
Labels: type: feature

#11936 Fix MapItem incorectly fetching water biomes on treasure maps
  paper-server/patches/sources/net/minecraft/world/item/MapItem.java.patch
Labels: type: bug

#11924 Prevent day cycle on the client when using fixed player time
  paper-server/patches/features/0017-Moonrise-optimisation-patches.patch
  paper-server/patches/features/0029-Optimize-Hoppers.patch
  paper-server/patches/sources/net/minecraft/server/MinecraftServer.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
Labels: type: bug

#11854 Biome - Fix snow accumulating in custom biomes without precipitation
  paper-server/patches/sources/net/minecraft/world/level/biome/Biome.java.patch
Labels: type: bug

#11918 Don't use delayed registries in impl anywhere
  paper-api/src/main/java/org/bukkit/Art.java
  paper-api/src/main/java/org/bukkit/Fluid.java
  paper-api/src/main/java/org/bukkit/JukeboxSong.java
  paper-api/src/main/java/org/bukkit/MusicInstrument.java
  paper-api/src/main/java/org/bukkit/Sound.java
  paper-api/src/main/java/org/bukkit/UnsafeValues.java
  paper-api/src/main/java/org/bukkit/attribute/Attribute.java
  paper-api/src/main/java/org/bukkit/block/Biome.java
  paper-api/src/main/java/org/bukkit/block/banner/Pattern.java
  paper-api/src/main/java/org/bukkit/block/banner/PatternType.java
  paper-api/src/main/java/org/bukkit/damage/DamageType.java
  paper-api/src/main/java/org/bukkit/enchantments/Enchantment.java
  paper-api/src/main/java/org/bukkit/entity/Wolf.java
  paper-api/src/main/java/org/bukkit/generator/structure/Structure.java
  paper-api/src/main/java/org/bukkit/inventory/ItemStack.java
  paper-api/src/main/java/org/bukkit/inventory/meta/trim/TrimMaterial.java
  paper-api/src/main/java/org/bukkit/inventory/meta/trim/TrimPattern.java
  paper-api/src/main/java/org/bukkit/potion/PotionEffect.java
  paper-server/src/main/java/io/papermc/paper/datacomponent/PaperDataComponentType.java
  paper-server/src/main/java/io/papermc/paper/datacomponent/item/PaperBannerPatternLayers.java
  paper-server/src/main/java/io/papermc/paper/util/Holderable.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftArt.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftFluid.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftGameEvent.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftJukeboxSong.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftMusicInstrument.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftRegistry.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftSound.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
  paper-server/src/main/java/org/bukkit/craftbukkit/attribute/CraftAttribute.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBanner.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBiome.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/banner/CraftPatternType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/damage/CraftDamageType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/enchantments/CraftEnchantment.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftCat.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntityType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftFrog.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftVillager.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftWolf.java
  paper-server/src/main/java/org/bukkit/craftbukkit/generator/structure/CraftStructure.java
  paper-server/src/main/java/org/bukkit/craftbukkit/generator/structure/CraftStructureType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftItemType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMenuType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaBanner.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/trim/CraftTrimMaterial.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/trim/CraftTrimPattern.java
  paper-server/src/main/java/org/bukkit/craftbukkit/legacy/enums/EnumEvil.java
  paper-server/src/main/java/org/bukkit/craftbukkit/map/CraftMapCursor.java
  paper-server/src/main/java/org/bukkit/craftbukkit/potion/CraftPotionEffectType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/potion/CraftPotionType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/util/CraftMagicNumbers.java
  paper-server/src/test/java/org/bukkit/registry/PerRegistryTest.java
  paper-server/src/test/java/org/bukkit/registry/RegistryConversionTest.java
Labels: type: bug

#11816 MenuType API addition InventoryView Builders
  build-data/paper.at
  paper-api/src/main/java/org/bukkit/Bukkit.java
  paper-api/src/main/java/org/bukkit/Server.java
  paper-api/src/main/java/org/bukkit/entity/HumanEntity.java
  paper-api/src/main/java/org/bukkit/inventory/MenuType.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/InventoryViewBuilder.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/LocationInventoryViewBuilder.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/MerchantInventoryViewBuilder.java
  paper-api/src/main/java/org/bukkit/inventory/view/builder/package-info.java
  paper-server/patches/sources/net/minecraft/world/inventory/AbstractContainerMenu.java.patch
  paper-server/patches/sources/net/minecraft/world/inventory/ChestMenu.java.patch
  paper-server/patches/sources/net/minecraft/world/inventory/MerchantMenu.java.patch
  paper-server/patches/sources/net/minecraft/world/inventory/ShulkerBoxMenu.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java
  paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftContainer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMenuType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/util/CraftMenus.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAbstractInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAbstractLocationInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftAccessLocationInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftBlockEntityInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftDoubleChestInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftMerchantInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/CraftStandardInventoryViewBuilder.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/view/builder/package-info.java
Labels: type: feature

#11868 Feat: Add 'with' methods to CommandSourceStack
  paper-api/src/main/java/io/papermc/paper/command/brigadier/CommandSourceStack.java
  paper-server/patches/features/0009-Fix-entity-type-tags-suggestions-in-selectors.patch
  paper-server/patches/sources/net/minecraft/commands/CommandSourceStack.java.patch
  paper-server/src/main/java/io/papermc/paper/command/brigadier/PaperCommandSourceStack.java
Labels: type: feature

#11914 Disallow calling JavaPlugin#getCommand during onEnable for Paper plugins
  paper-api/src/main/java/org/bukkit/plugin/java/JavaPlugin.java
Labels: type: feature

#11898 Make CommandSourceStack respect hidden players
  paper-server/patches/features/0009-Fix-entity-type-tags-suggestions-in-selectors.patch
  paper-server/patches/sources/net/minecraft/commands/CommandSourceStack.java.patch
Labels: type: bug

#11838 Add EntityEffectTickEvent
  paper-api/src/main/java/io/papermc/paper/event/entity/EntityEffectTickEvent.java
  paper-server/patches/sources/net/minecraft/world/effect/HealOrHarmMobEffect.java.patch
  paper-server/patches/sources/net/minecraft/world/effect/MobEffect.java.patch
  paper-server/patches/sources/net/minecraft/world/effect/MobEffectInstance.java.patch
Labels: type: feature

#11959 Deprecate Turtle#isDigging
  paper-api/src/main/java/org/bukkit/entity/Turtle.java
  paper-server/patches/sources/net/minecraft/world/level/block/entity/BrewingStandBlockEntity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftTurtle.java
Labels: scope: api

#11892 Fix client visual desync if cooldown events are cancelled
  paper-server/patches/sources/net/minecraft/world/item/ServerItemCooldowns.java.patch
Labels: type: bug

#11941 Fix unstable Suggestion comparison
  paper-server/patches/sources/com/mojang/brigadier/suggestion/IntegerSuggestion.java.patch
  paper-server/patches/sources/com/mojang/brigadier/suggestion/Suggestion.java.patch
Labels: type: bug

#11958 Expose all possible block data states
  paper-api/src/main/java/org/bukkit/block/BlockType.java
  paper-server/src/main/java/org/bukkit/craftbukkit/block/CraftBlockType.java
Labels: type: feature

#11899 Call PlayerItemDamageEvent for tridents
  paper-server/patches/features/0028-Optimize-Hoppers.patch
  paper-server/patches/sources/net/minecraft/world/item/ItemStack.java.patch
Labels: type: bug

#11961 Remove deprecation from EntityRemoveEvent
  paper-api/src/main/java/org/bukkit/event/entity/EntityRemoveEvent.java
Labels: type: feature

#12008 Check for empty when sending equipment changes
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: bug, scope: api

#11907 Add RayTraceConfigurationBuilder
  paper-api/src/main/java/io/papermc/paper/raytracing/PositionedRayTraceConfigurationBuilder.java
  paper-api/src/main/java/io/papermc/paper/raytracing/RayTraceTarget.java
  paper-api/src/main/java/org/bukkit/World.java
  paper-server/src/main/java/io/papermc/paper/raytracing/PositionedRayTraceConfigurationBuilderImpl.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
Labels: type: feature, status: input wanted

#12007 Fix wrong piston world border check
  paper-server/patches/sources/net/minecraft/world/level/block/piston/PistonBaseBlock.java.patch
Labels: type: bug

#12010 Use proper default for setting null display background color
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftTextDisplay.java
Labels: type: bug, scope: api

#11998 [ci skip] fix and improvements for docs in ConsumeEffect component
  paper-api/src/main/java/io/papermc/paper/datacomponent/item/consumable/ConsumeEffect.java
Labels: type: documentation, scope: api

#11940 Add PlayerLoadedWorldEvent
  paper-api/src/main/java/io/papermc/paper/event/player/PlayerClientLoadedWorldEvent.java
  paper-server/patches/features/0029-Optimise-collision-checking-in-player-move-packet-ha.patch
  paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/player/Player.java.patch
Labels: type: feature

#11995 Add Player#give
  paper-api/src/main/java/io/papermc/paper/entity/PlayerGiveResult.java
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-server/src/main/java/io/papermc/paper/entity/PaperPlayerGiveResult.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: feature, scope: api

#12047 Fix activation range config and water animal status
  paper-server/patches/features/0003-Entity-Activation-Range-2.0.patch
  paper-server/src/main/java/io/papermc/paper/entity/activation/ActivationType.java
Labels: type: bug
