Repository PaperMC/Paper, pull requests merged in 2025-04, with the labels that each got.

#12344 Add support for bonus chest configuration in WorldCreator
  paper-api/src/main/java/org/bukkit/World.java
  paper-api/src/main/java/org/bukkit/WorldCreator.java
  paper-server/patches/sources/net/minecraft/world/level/GameRules.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftWorld.java
Labels: type: feature, size: small, scope: api

#12069 Add vault change state event
  paper-api/src/main/java/io/papermc/paper/event/block/VaultChangeStateEvent.java
  paper-server/patches/sources/net/minecraft/world/level/block/entity/vault/VaultBlockEntity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/block/data/CraftBlockData.java
Labels: scope: api

#12310 FishHook - add method to retrieve
  paper-api/src/main/java/org/bukkit/entity/FishHook.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftFishHook.java
Labels: type: feature, scope: api

#12410 Use correct placed block position for sound
  paper-server/patches/features/0027-Optimize-Hoppers.patch
  paper-server/patches/sources/net/minecraft/world/InteractionResult.java.patch
  paper-server/patches/sources/net/minecraft/world/item/BlockItem.java.patch
  paper-server/patches/sources/net/minecraft/world/item/ItemStack.java.patch
Labels: build-pr-jar

#11960 Fix inconsistencies between offline/online spawn position getter
  paper-api/src/main/java/org/bukkit/OfflinePlayer.java
  paper-api/src/main/java/org/bukkit/entity/HumanEntity.java
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftOfflinePlayer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: bug, scope: api

#12307 Fix handling of resultant crafting container from craftItemResult
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
Labels: type: bug

#12031 Add methods for Armadillo
  paper-api/src/main/java/org/bukkit/entity/Armadillo.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftArmadillo.java
Labels: type: feature, scope: api

#12296 Fix unnecessary map data saves (#12295)
  paper-server/patches/sources/net/minecraft/world/level/saveddata/maps/MapItemSavedData.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/map/CraftMapCanvas.java
Labels: scope: performance

#11853 Add combat tracker API
  build-data/paper.at
  paper-api/src/main/java/io/papermc/paper/InternalAPIBridge.java
  paper-api/src/main/java/io/papermc/paper/world/damagesource/CombatEntry.java
  paper-api/src/main/java/io/papermc/paper/world/damagesource/CombatTracker.java
  paper-api/src/main/java/io/papermc/paper/world/damagesource/FallLocationType.java
  paper-api/src/main/java/io/papermc/paper/world/damagesource/FallLocationTypeImpl.java
  paper-api/src/main/java/org/bukkit/entity/LivingEntity.java
  paper-server/patches/sources/net/minecraft/world/damagesource/CombatTracker.java.patch
  paper-server/src/main/java/io/papermc/paper/PaperServerInternalAPIBridge.java
  paper-server/src/main/java/io/papermc/paper/world/damagesource/PaperCombatEntryWrapper.java
  paper-server/src/main/java/io/papermc/paper/world/damagesource/PaperCombatTrackerWrapper.java
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftLivingEntity.java
Labels: type: feature

#12269 Fix save/load NaN Entity Motion
  paper-server/patches/features/0015-Moonrise-optimisation-patches.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
  paper-server/src/main/java/io/papermc/paper/util/MCUtil.java
Labels: type: bug

#11792 Parity for respawn events
  paper-api/src/main/java/com/destroystokyo/paper/event/player/PlayerPostRespawnEvent.java
  paper-api/src/main/java/io/papermc/paper/event/player/AbstractRespawnEvent.java
  paper-api/src/main/java/org/bukkit/event/player/PlayerRespawnEvent.java
  paper-server/patches/features/0015-Moonrise-optimisation-patches.patch
  paper-server/patches/features/0023-Incremental-chunk-and-player-saving.patch
  paper-server/patches/sources/net/minecraft/server/level/ServerPlayer.java.patch
  paper-server/patches/sources/net/minecraft/server/players/PlayerList.java.patch
Labels: type: feature, status: accepted
