Repository PaperMC/Paper, pull requests merged in 2025-05, with the labels that each got.

#12216 Fix ItemStack amount issues with Chat Components
  paper-api/src/main/java/org/bukkit/inventory/ItemFactory.java
  paper-api/src/main/java/org/bukkit/inventory/ItemStack.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftItemFactory.java
Labels: type: bug

#12193 Add a method on InventoryView to get the MenuType
  build-data/paper.at
  paper-api/src/main/java/org/bukkit/inventory/InventoryView.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftContainer.java
  paper-server/src/main/java/org/bukkit/craftbukkit/inventory/CraftInventoryView.java
Labels: type: feature, scope: api

#12197 Infer block entity data in brigadier blockstate argument
  paper-server/src/main/java/io/papermc/paper/command/brigadier/argument/VanillaArgumentProviderImpl.java
Labels: type: bug, scope: api

#12308 Pass correct draw strength for EntityShootBowEvent
  paper-server/patches/sources/net/minecraft/world/entity/monster/AbstractSkeleton.java.patch
  paper-server/patches/sources/net/minecraft/world/entity/monster/Illusioner.java.patch
  paper-server/patches/sources/net/minecraft/world/item/BowItem.java.patch
  paper-server/patches/sources/net/minecraft/world/item/CrossbowItem.java.patch
  paper-server/patches/sources/net/minecraft/world/item/ProjectileWeaponItem.java.patch
Labels: type: bug, scope: api

#12297 Disable Item Obfuscation for entity related stacks
  paper-server/patches/sources/net/minecraft/network/syncher/EntityDataSerializers.java.patch
Labels: type: bug

#12273 Add configuration interface to expose certain config values
  paper-api/src/main/java/io/papermc/paper/configuration/ServerConfiguration.java
  paper-api/src/main/java/org/bukkit/Bukkit.java
  paper-api/src/main/java/org/bukkit/Server.java
  paper-server/src/main/java/io/papermc/paper/configuration/PaperServerConfiguration.java
  paper-server/src/main/java/org/bukkit/craftbukkit/CraftServer.java
Labels: type: feature, scope: api

#12221 Expand PlayerDeathEvent API
  paper-api/src/main/java/org/bukkit/event/entity/PlayerDeathEvent.java
  paper-server/patches/features/0015-Moonrise-optimisation-patches.patch
  paper-server/patches/features/0023-Incremental-chunk-and-player-saving.patch
  paper-server/patches/features/0025-Optional-per-player-mob-spawns.patch
  paper-server/patches/features/0026-Improve-cancelling-PreCreatureSpawnEvent-with-per-pl.patch
  paper-server/patches/sources/net/minecraft/server/level/ServerPlayer.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/event/CraftEventFactory.java
Labels: type: feature, scope: api

#12303 Update visual fire handling with TriState support
  paper-api/src/main/java/org/bukkit/entity/Entity.java
  paper-server/patches/features/0015-Moonrise-optimisation-patches.patch
  paper-server/patches/sources/net/minecraft/world/entity/Entity.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftEntity.java
Labels: type: feature, scope: api

#12530 Properly save level data async
  paper-server/patches/features/0023-Incremental-chunk-and-player-saving.patch
Labels: build-pr-jar

#12165 Add FishHookStateChangeEvent to detect fishing hook state transitions.
  paper-api/src/main/java/io/papermc/paper/event/entity/FishHookStateChangeEvent.java
  paper-api/src/main/java/org/bukkit/entity/FishHook.java
  paper-api/src/main/java/org/bukkit/event/player/PlayerFishEvent.java
  paper-server/patches/sources/net/minecraft/world/entity/projectile/FishingHook.java.patch
Labels: type: feature, scope: api

#11903 Add API for client-side signs
  paper-api/src/main/java/io/papermc/paper/event/packet/UncheckedSignChangeEvent.java
  paper-api/src/main/java/org/bukkit/entity/Player.java
  paper-server/patches/sources/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  paper-server/src/main/java/org/bukkit/craftbukkit/entity/CraftPlayer.java
Labels: type: feature
